# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

matrix:
  include:
    - os: linux
      env: CONFIG=Release TOOLCHAIN=default
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=default
    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=gcc
    - os: linux
      env: CONFIG=Release TOOLCHAIN=analyze
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=analyze
    - os: linux
      env: CONFIG=Release TOOLCHAIN=sanitize-address
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=sanitize-address
    - os: linux
      env: CONFIG=Release TOOLCHAIN=sanitize-leak
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=sanitize-leak
install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"

script:
  - build.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose --test

branches:
  except:
    - /^pr\..*/