language: cpp

sudo: required

dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Info about OS
  - uname -a
 
script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - cd build && cmake ..
  - make