language: cpp

sudo: false

dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
install:
  # Info about OS
  - uname -a
script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - cd build && cmake .. -DCMAKE_CXX_COMPILER=g++6
  - make