language: cpp

sudo: false

dist: trusty

matrix:
  include:
     - os: linux
    addons:
      apt:
        sources:
          - george-edison55-precise-backports
        packages:
          - cmake-data
          - cmake

before_install:
  - eval "${MATRIX_EVAL}"

install:
  # Info about OS
  - uname -a
script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - cd build && cmake ..
  - make