version: 1.0.{build}

image: "Visual Studio 2015"

matrix:
	fast_finish: true
	allow_failures:
		- platform: x86
		  configuration: Debug
		- platform: x86
		  configuration: Release
		  
platform: x86
configuration: Release

build:
	parallel: true
	project: iotchain.sln
	verbosity: minimal

build_script:
	- ps: |
		msbuild -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS "C:\projects\iotchain\iotchain.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
		|